### PR TITLE
Calculate spotlight exponent to implement smooth falloff

### PR DESCRIPTION
**Pull request by rdb**
I noticed in #81 that spot lights are all converted with a hard cutoff, as though the inner cone is set to the outer cone.

The KHR_lights_punctual spec says that engines that do not support a separate inner angle (including Panda3D) should treat it as though it were set to 0 (implying a fully smooth falloff).  So, this PR sets a smooth exponent when the inner angle is a value lower than the outer angle.

There is a formula in the spec suggesting how we implement the falloff.  I did some curve fitting and determined that by calculating the exponent using `2 * (pi / (outer * 2)) ^ 2` we can get pretty close: (purple is the spec falloff, black is our exponential falloff).
image
(Play with it yourself [here](https://www.desmos.com/calculator/74mvgiwa9i).)

However, as you can see, it doesn't *quite* reach 0 at the outer cone (red line), so there is still a bit of an abrupt transition.  If we wanted to do eliminate the transition entirely, we could increase that last `^ 2` to a higher value, which would result in a smooth cutoff but a sharper overall falloff—but that's a pretty big trade-off though given that the total amount of light emitted ends up significantly lower that way.

Thoughts?

I believe this won't work in the viewer since simplepbr does not appear to implement the spot exponent.

### CODE REVIEW

**Comment by Moguri** [comment]
Thanks for looking into this! Properly handling inner and outer cone values has been on my todo list for a while, and this PR lines up with how I was expecting this to look. Do you have a screenshot handy of the new transition? I can look into adding spot exponent support to simplepbr so we can get gltf-viewer working correctly.

**Comment by rdb** [comment]
Yes, here's what it looks like, with e=2 (the value in the PR):
image
These show the effect at e=2.5 and e=3.  You can see that e=3 effectively eliminates the harsh cutoff, but at the cost of making the cutoff *significantly* smaller (and so reducing )
image
image

Here is the corresponding falloff chart for that last screenshot, with e=3:
image

I am personally leaning towards going with e=2, at least as a starting point, to maximize accuracy, and consider adding a better falloff system to Panda.

**Comment by rdb** [comment]
On the other hand, perhaps most users will find it more important to have a smooth falloff than to have very accurate light distribution (which can perhaps be compensated for in other ways).  Changing `e = 2` to `e = 8 / 3` in the code may provide a "good enough" middle ground that has a nearly imperceptible cutoff, while being at the worst point in the curve half as bright as it should be:
image image

**Comment by rdb** [comment]
If we consider the smoothness of the cutoff to be most important, there is an alternative way to calculate the spot exponent `s`, by giving it a maximum threshold `t` for the transition:
https://www.desmos.com/calculator/ge5pnjhz3u
We could then cap it to the value calculated by my other method to behave properly for large cutoff angles.

**Comment by Moguri** [comment]
I am inclined to go with what most users will expect rather than chasing the spec on this. Especially, as you suggested, we can update this if and when Panda's falloff controls improve. So, of the various `e` values you've shown, `e = 8/3` seems the best so far. `e = 2` seems pretty harsh and `e = 3` is getting too inaccurate for my tastes. However, the alternative way to calculate the spot exponent sounds interesting as well.

**Comment by Moguri** [comment]
Thanks!

**Pull request merged**
