### PR TITLE
Fix coordinate system conversion issue

### PR DESCRIPTION
**Pull request by rdb**
The vertices also need to be transformed.  Without this, models don't import correctly.

### CODE REVIEW

**Comment by Moguri** [comment]
What kind of testing have you done for this?

**Comment by Moguri** [comment]
I'll probably just merge this. However, I think there may be more changes necessary.

**Comment by rdb** [comment]
I didn't do a lot of testing; I just tested the basic Lantern model from the glTF test repository, which does not import correctly at all without this change.

That said, because panda3d-gltf doesn't support importing matrix transforms, models with matrices still won't load correctly, so maybe I'll add that to this PR.

**Comment by rdb** [comment]
@Moguri Nodes with matrices are now supported.  This means that models from the glTF sample repository that had a root node with a Z-Up to Y-Up matrix (but used separate translation/rotation on all other nodes) will now import properly upright again.

I think I also fixed the axis conversion issues for rigged and animated models; CesiumMan's walk cycle seems to import just fine after my latest commit (there are two joints jutting out of the bottom, but it was that way before these changes too, so that must be a separate problem).

What other changes do you think would be necessary for this to be merged?

**Comment by Moguri** [comment]
This looks good to me for merging. If we run into more issues, they can be fixed then. I will also try to do some more testing. There were some of the sample models that gave me grief, but I don't remember which ones they were at the moment. Thanks!

**Pull request merged**
