### PR TITLE
Force normalization of joint weights

### PR DESCRIPTION
**Pull request by el-dee**
This PR add a normalization of the joint weights to cope with malformed assets. (Many generated using the common tool FBX2glTF, see https://github.com/facebookincubator/FBX2glTF/pull/176)

The normalization is performed only if the weights are stored in float, otherwise this extra normalization will break the appearance of the mesh (see https://github.com/KhronosGroup/glTF/pull/1749/files)

### CODE REVIEW

**Comment by rdb** [comment]
I agree normalization seems like a good idea.  Though, storing this state as a member on Converter is a little hacky (since it's a per-primitive state).

**Comment by el-dee** [comment]
Ah, you're right. I thought that an exporter tool would behave the same way for all the primitives, but I guess nothing prevent someone to use float joint weights for some prims and integer weights for some others.

Unless I'm wrong, the normalization flag should then be stored in a dict, indexed with the geom_node of the prim.

**Comment by rdb** [comment]
Maybe it would be better to just reprocess the weights column right in load_primitive (similar to the "Flip UVs" step)?  Then you don't have to pass anything around.

I suspect that this change also doesn't work with GPU animation (which uses the transform_weight column) and only with CPU animation (which uses the TransformBlendTable), and doing the above would fix that as well.

**Comment by el-dee** [comment]
Indeed, I modified the code accordingly and it still work without the need to keep the normalization flag.

**Review by rdb — APPROVED** [review]
LGTM.  I just verified, to be sure, that Panda indeed reads the w channel as 0 and not 1 if there are fewer than 4 channels present, so this should work in all cases.

**Pull request merged**
